# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  postgresql

# Изменяет текущую временную зону.
before_install:
- export TZ=Europe/Moscow
- date
- psql -c 'create database tracker;' -U postgres
-
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
      - CODECOV_TOKEN='a18842a4-1622-4bff-97f4-40141c97128b'

# Отправлять уведомление на почтуmailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mailto:rusanov_roman@icloud.com
    on_success: never # default: change
    on_failure: always # default: always